#!/usr/bin/env python3
"""
Securely configure cloud-backend API keys for Cohortex.

- Reads secrets with getpass (never echoed, never in shell history).
- Writes them to a local `.env` that is gitignored (verified before writing).
- chmod 0600 on macOS/Linux; never prints a key back.
Ollama (the default backend) needs no key, so every value here is optional.

    python setup_env.py
"""
from __future__ import annotations

import getpass
import os
import stat
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
BAK_PATH = ROOT / ".env.bak"
GITIGNORE = ROOT / ".gitignore"

# (name, description, required)
VARS: list[tuple[str, str, bool]] = [
    ("OPENAI_API_KEY", "OpenAI key — 'openai' and 'grok' backends", False),
    ("ANTHROPIC_API_KEY", "Anthropic key — 'anthropic' backend", False),
    ("GEMINI_API_KEY", "Google Gemini key — 'gemini' backend", False),
    ("XAI_API_KEY", "xAI key — 'grok' backend", False),
]


def load_existing() -> dict[str, str]:
    values: dict[str, str] = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                values[k.strip()] = v.strip()
    return values


def ensure_gitignored() -> None:
    ignored = False
    if GITIGNORE.exists():
        patterns = {ln.strip() for ln in GITIGNORE.read_text(encoding="utf-8").splitlines()}
        ignored = ".env" in patterns or "*.env" in patterns
    if not ignored:
        with GITIGNORE.open("a", encoding="utf-8") as f:
            f.write("\n# added by setup_env.py — never commit secrets\n.env\n")
        print("  ! .env was not gitignored — added it to .gitignore")


def secret_input(prompt: str) -> str:
    if sys.stdin is not None and sys.stdin.isatty():
        try:
            return getpass.getpass(prompt).strip()
        except Exception:  # noqa: BLE001
            pass
    sys.stdout.write(prompt)
    sys.stdout.flush()
    line = sys.stdin.readline()
    if not line:
        raise EOFError
    return line.strip()


def prompt_for(name: str, desc: str, current: str) -> str:
    have = " [set]" if current else ""
    print(f"\n{name}{have}\n  {desc}")
    hint = "Enter to keep current" if current else "optional, Enter to skip"
    try:
        value = secret_input(f"  value ({hint}): ")
    except EOFError:
        return current
    return value or current


def write_env(values: dict[str, str]) -> None:
    if ENV_PATH.exists():
        ENV_PATH.replace(BAK_PATH)
    lines = ["# Local secrets — generated by setup_env.py. Do NOT commit this file.", ""]
    for name, _, _ in VARS:
        if values.get(name):
            lines.append(f"{name}={values[name]}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(ENV_PATH, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def main() -> int:
    print("Cohortex secure key setup — values are hidden as you type.")
    ensure_gitignored()
    existing = load_existing()
    values = {name: prompt_for(name, desc, existing.get(name, "")) for name, desc, _ in VARS}
    write_env(values)
    configured = [n for n, _, _ in VARS if values.get(n)]
    print(f"\n✓ Wrote {ENV_PATH.name} with: {', '.join(configured) or '(nothing — using local Ollama)'}")
    print("  This file is gitignored and readable only by you. Never commit it.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\naborted.")
        sys.exit(130)
